### ISSUE TITLE
ToggleSections plugin breaking settings..

### ISSUE THREAD

**Issue by JourneyOver** [kettui/BetterDiscord-extensions#1]
Dunno if you are still updating ToggleSections plugin or not, but currently it seems to be breaking the settings menu. whenever I throw the plugin into the plugin folder the "betterdiscord" options menu completely disappears, if I take out the plugin the option menu comes back.

This is happening both with the default theme that discord comes with and pretty much any other theme as well.

**Comment by kettui** [comment]
Thanks for the heads up, I haven't had the plugin enabled myself for a while now so I wasn't aware of the issue. I'll look this up tonight after work.

**Comment by kettui** [comment]
Got to start a bit late, but the [new version](https://github.com/kettui/BetterDiscord-extensions/blob/master/plugins/ToggleSections/ToggleSections.plugin.js) is up now and everything should work as expected.  

Let me know if there are any issues, I'm happy to help.

**Comment by JourneyOver** [comment]
Somewhat works now, the options at least show the betterdiscord stuff now, but idk if you removed the option to toggle back or not but if I toggle the server list to hide it, I don't get the option to bring it back out. Only way to bring it back out is to go into the betterdiscord plugins and disable the plugin. :s

**Comment by kettui** [comment]
Does the toggler button disappear altogether, or does it become unclickable? I haven't been able to reproduce the issue with or without a custom theme, so I'll need some more information.

**Comment by JourneyOver** [comment]
it disappears altogether, but I just tested it without a theme and it was there so found out that's something to do with the theme I'm running.

**Comment by kettui** [comment]
Thanks, I'll look into it.

**Comment by JourneyOver** [comment]
Sounds good :) if it ends up being something you can't fix on your end though then don't worry about it ^^

**Comment by kettui** [comment]
[Fixed](https://github.com/kettui/BetterDiscord-extensions/blob/master/plugins/ToggleSections/ToggleSections.plugin.js) 🦊

**Comment by JourneyOver** [comment]
Everything seems to be working correctly now for the theme I'm using :) so guess I'm going to close this ^^ thanks
